#!/bin/bash
set -e

# ─── BibleHodl Community Init Script ───
# Run this once on a fresh deployment to bootstrap the instance.
# Creates: .env, admin keypair, default team, first invite codes.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/.env"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

echo ""
echo -e "${BOLD}⚡ BibleHodl Community Setup${NC}"
echo -e "────────────────────────────────────────"
echo ""

# ─── Check if already initialized ───
if [ -f "$ENV_FILE" ] && grep -q "INIT_COMPLETE=true" "$ENV_FILE" 2>/dev/null; then
  echo -e "${YELLOW}⚠️  This instance appears to already be initialized.${NC}"
  echo -e "   Remove INIT_COMPLETE=true from .env to re-run."
  echo ""
  read -p "Continue anyway? (y/N): " CONTINUE
  if [[ ! "$CONTINUE" =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
  fi
fi

# ─── Check dependencies ───
if ! command -v node &>/dev/null; then
  echo -e "${RED}Error: Node.js is required but not installed.${NC}"
  exit 1
fi

# ─── Gather community info ───
echo -e "${CYAN}Community Configuration${NC}"
echo ""

read -p "Community name: " COMMUNITY_NAME
if [ -z "$COMMUNITY_NAME" ]; then
  echo -e "${RED}Community name is required.${NC}"
  exit 1
fi

read -p "Domain (e.g. biblehodl.com): " DOMAIN
if [ -z "$DOMAIN" ]; then
  echo -e "${RED}Domain is required.${NC}"
  exit 1
fi

read -p "Primary color (hex, default #3b82f6): " PRIMARY_COLOR
PRIMARY_COLOR="${PRIMARY_COLOR:-#3b82f6}"

read -p "Community logo URL (optional): " COMMUNITY_LOGO_URL

# ─── Admin setup ───
echo ""
echo -e "${CYAN}Admin Account Setup${NC}"
echo ""

read -p "Admin first name: " ADMIN_FIRST_NAME
if [ -z "$ADMIN_FIRST_NAME" ]; then
  echo -e "${RED}Admin first name is required.${NC}"
  exit 1
fi

read -p "Admin last name: " ADMIN_LAST_NAME
if [ -z "$ADMIN_LAST_NAME" ]; then
  echo -e "${RED}Admin last name is required.${NC}"
  exit 1
fi

read -p "Admin email: " ADMIN_EMAIL
if [ -z "$ADMIN_EMAIL" ]; then
  echo -e "${RED}Admin email is required.${NC}"
  exit 1
fi

echo ""
echo -e "${CYAN}Nostr Keypair${NC}"
echo "The admin needs a Nostr keypair. You can:"
echo "  1) Generate a new keypair now"
echo "  2) Enter an existing nsec"
echo ""
read -p "Choice (1/2): " KEY_CHOICE

if [ "$KEY_CHOICE" = "2" ]; then
  read -s -p "Enter nsec: " ADMIN_NSEC
  echo ""
  if [ -z "$ADMIN_NSEC" ]; then
    echo -e "${RED}nsec is required.${NC}"
    exit 1
  fi
  # Derive npub from nsec
  KEYS_JSON=$(node --input-type=module -e "
    import { nip19, getPublicKey } from 'nostr-tools';
    const { data: sk } = nip19.decode('$ADMIN_NSEC');
    const pk = getPublicKey(sk);
    console.log(JSON.stringify({
      nsec: '$ADMIN_NSEC',
      npub: nip19.npubEncode(pk),
      pubkey: pk
    }));
  " 2>/dev/null) || {
    echo -e "${RED}Invalid nsec key.${NC}"
    exit 1
  }
else
  # Generate new keypair
  KEYS_JSON=$(node --input-type=module -e "
    import { generateSecretKey, getPublicKey, nip19 } from 'nostr-tools';
    const sk = generateSecretKey();
    const pk = getPublicKey(sk);
    console.log(JSON.stringify({
      nsec: nip19.nsecEncode(sk),
      npub: nip19.npubEncode(pk),
      pubkey: pk
    }));
  " 2>/dev/null) || {
    echo -e "${RED}Failed to generate keys. Is nostr-tools installed?${NC}"
    exit 1
  }
fi

ADMIN_NSEC=$(echo "$KEYS_JSON" | node -e "process.stdout.write(JSON.parse(require('fs').readFileSync(0,'utf8')).nsec)")
ADMIN_NPUB=$(echo "$KEYS_JSON" | node -e "process.stdout.write(JSON.parse(require('fs').readFileSync(0,'utf8')).npub)")
ADMIN_PUBKEY=$(echo "$KEYS_JSON" | node -e "process.stdout.write(JSON.parse(require('fs').readFileSync(0,'utf8')).pubkey)")

# ─── Generate secrets ───
SESSION_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
BLOSSOM_PASS=$(node -e "console.log(require('crypto').randomBytes(16).toString('hex'))")

# ─── Generate invite codes ───
INVITE_CODES=()
for i in {1..5}; do
  CODE=$(node -e "console.log(require('crypto').randomBytes(4).toString('hex').toUpperCase())")
  INVITE_CODES+=("$CODE")
done

# ─── Write .env ───
cat > "$ENV_FILE" <<EOF
# ─── BibleHodl Community Configuration ───
# Generated by init.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

DOMAIN=$DOMAIN
COMMUNITY_NAME=$COMMUNITY_NAME
COMMUNITY_LOGO_URL=$COMMUNITY_LOGO_URL
PRIMARY_COLOR=$PRIMARY_COLOR

ADMIN_NPUB=$ADMIN_NPUB
ADMIN_EMAIL=$ADMIN_EMAIL

DATABASE_URL=file:/data/app.db

NEXT_PUBLIC_RELAY_URL=wss://relay.$DOMAIN
NEXT_PUBLIC_BLOSSOM_URL=https://files.$DOMAIN

CPDV_API_URL=https://cpdv-bible-production.up.railway.app
CPDV_API_KEY=

SESSION_SECRET=$SESSION_SECRET

# Blossom admin dashboard (https://files.$DOMAIN/admin)
BLOSSOM_ADMIN_USER=admin
BLOSSOM_ADMIN_PASS=$BLOSSOM_PASS

INIT_COMPLETE=true
EOF

echo -e "${GREEN}✓ .env written${NC}"

# ─── Bootstrap database ───
echo ""
echo -e "${CYAN}Bootstrapping database...${NC}"

cd "$PROJECT_DIR"

# Run migrations
npx prisma migrate deploy --schema=./prisma/schema.prisma 2>/dev/null

# Create default team + admin member + invite codes
node -e "
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function bootstrap() {
  // Check if already bootstrapped
  const existing = await prisma.team.count();
  if (existing > 0) {
    console.log('Database already has teams — skipping bootstrap.');
    return;
  }

  // Create default team
  const team = await prisma.team.create({
    data: {
      name: '$COMMUNITY_NAME',
      description: 'Default community team',
      createdBy: '$ADMIN_PUBKEY',
    },
  });

  // Create admin member
  await prisma.member.create({
    data: {
      teamId: team.id,
      pubkey: '$ADMIN_PUBKEY',
      firstName: $(node -e "process.stdout.write(JSON.stringify('$ADMIN_FIRST_NAME'))"),
      lastName: $(node -e "process.stdout.write(JSON.stringify('$ADMIN_LAST_NAME'))"),
      email: $(node -e "process.stdout.write(JSON.stringify('$ADMIN_EMAIL'))"),
      role: 'owner',
    },
  });

  // Create invite codes
  const codes = $(node -e "process.stdout.write(JSON.stringify([$(printf '"%s",' "${INVITE_CODES[@]}" | sed 's/,$//')]))");
  const expiry = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000); // 30 days

  for (const code of codes) {
    await prisma.invite.create({
      data: {
        teamId: team.id,
        code,
        createdBy: '$ADMIN_PUBKEY',
        expiresAt: expiry,
      },
    });
  }

  console.log('Database bootstrapped successfully.');
}

bootstrap()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.\$disconnect());
" 2>/dev/null

echo -e "${GREEN}✓ Database bootstrapped${NC}"

# ─── Output summary ───
echo ""
echo -e "────────────────────────────────────────"
echo -e "${BOLD}${GREEN}⚡ Setup Complete!${NC}"
echo -e "────────────────────────────────────────"
echo ""
echo -e "${BOLD}Community:${NC} $COMMUNITY_NAME"
echo -e "${BOLD}Domain:${NC}    $DOMAIN"
echo -e "${BOLD}Relay:${NC}     wss://relay.$DOMAIN"
echo -e "${BOLD}Files:${NC}     https://files.$DOMAIN"
echo ""
echo -e "${BOLD}${CYAN}Admin Credentials${NC}"
echo -e "────────────────────────────────────────"
echo -e "${BOLD}Name:${NC}   $ADMIN_FIRST_NAME $ADMIN_LAST_NAME"
echo -e "${BOLD}Email:${NC}  $ADMIN_EMAIL"
echo -e "${BOLD}npub:${NC}   $ADMIN_NPUB"
echo -e "${BOLD}${RED}nsec:${NC}   $ADMIN_NSEC"
echo ""
echo -e "${YELLOW}⚠️  SAVE THE NSEC KEY ABOVE — IT WILL NOT BE SHOWN AGAIN${NC}"
echo ""
echo -e "${BOLD}${CYAN}Invite Codes${NC} (valid 30 days)"
echo -e "────────────────────────────────────────"
for CODE in "${INVITE_CODES[@]}"; do
  echo -e "  ${GREEN}$CODE${NC}"
done
echo ""
echo -e "${BOLD}${CYAN}Blossom Admin${NC}"
echo -e "────────────────────────────────────────"
echo -e "${BOLD}URL:${NC}      https://files.$DOMAIN/admin"
echo -e "${BOLD}User:${NC}     admin"
echo -e "${BOLD}Password:${NC} $BLOSSOM_PASS"
echo ""
echo -e "────────────────────────────────────────"
echo -e "Next steps:"
echo -e "  1. Save the admin credentials above"
echo -e "  2. Run: ${BOLD}docker compose up -d${NC}"
echo -e "  3. Visit: ${BOLD}https://$DOMAIN${NC}"
echo -e "  4. Admin can log in with their nsec — no invite needed"
echo -e "  5. Share invite codes with initial members"
echo ""
